### ISSUE TITLE
Feature Request: Seattle! :smile:

### ISSUE THREAD

**Issue by JaimeLynSchatz** [mozilla/ascendproject#3]
I see that Louisiana is next on the list, but if you're casting about for a third city, I humbly present Seattle as an option and offer whatever help I can lend to make it happen.

Given the extraordinary popularity of the Ada Developers Academy here in the Seattle area, there's clearly a huge demand for a project like this. There's both a big supply of potential students _and_ a big supply of potential volunteers. While many folks here have benefited from the local tech boom, many more were left in the dust. Both the students and the OS world would benefit from a Project Ascend: Seattle.

**Comment by lsblakk** [comment]
Thanks for putting this forward, am keeping a list of potential expansion cities - you're on it!
