### ISSUE TITLE
On the blog page, show the author automatically

### ISSUE THREAD

**Issue by kronda** [mozilla/ascendproject#84]

**Comment by aokoye** [comment]
I'll volunteer to work on this.

**Comment by theaverageguy** [comment]
http://ascendproject.org/index.html 
This page has authors in some cases and not in all. Do we need to automate this that we get the author automatically.?

**Comment by n8chz** [comment]
I have no idea, but I'm delighted to see any activity on anything related to Ascend Project.

**Comment by bugzPDX** [comment]
Each participant formatted their own index.html. Some chose to include an author:
https://github.com/mozilla/ascendproject/blob/gh-pages/participants/portland/barbara/index.html

And some not:
https://github.com/mozilla/ascendproject/blob/gh-pages/participants/portland/david/index.html

So I guess it depends upon whether the anyone wants to require there be an author.

**Comment by theaverageguy** [comment]
So are we planning to fix it?
